
:toc:
:toclevels: 2

= InvisiMole -- Indicators of Compromise

== InvisiMole's backdoors Indicators of Compromise

For a description of InvisiMole's RC2FM and RC2CL backdoors, please see the article about
https://www.welivesecurity.com/2018/06/07/invisimole-equipped-spyware-undercover/[InvisiMole]
on https://www.welivesecurity.com[WeLiveSecurity].

=== ESET detection names
- Win32/InvisiMole.A
- Win32/InvisiMole.B
- Win32/InvisiMole.C
- Win32/InvisiMole.D
- Win64/InvisiMole.B
- Win64/InvisiMole.C
- Win64/InvisiMole.D

=== SHA-1 hashes
----
5EE6E0410052029EAFA10D1669AE3AA04B508BF9
2FCC87AB226F4A1CC713B13A12421468C82CD586
B6BA65A48FFEB800C29822265190B8EAEA3935B1
C8C4B6BCB4B583BA69663EC3AED8E1E01F310F9F
A5A20BC333F22FD89C34A532680173CBCD287FF8
----

=== Files and folders
==== RC2FM
----
%APPDATA%\Microsoft\Internet Explorer\Cache\AMB6HER8\
    %volumeSerialNumber%.dat
    content.dat
    cache.dat
    index.dat
%APPDATA%\Microsoft\Internet Explorer\Cache\MX0ROSB1\
    content.dat
    index.dat
    %random%.%ext%
%APPDATA%\Microsoft\Internet Explorer\Cache\index0.dat
----
==== RC2CL
----
Winrar\
    comment.txt
    descript.ion
    Default.SFX
    WinRAR.exe
    main.ico
fl_%timestamp%\strcn%num%\
    fdata.dat
    index.dat
~mrc_%random%.tmp
~src_%random%.tmp
~wbc_%random%.tmp
sc\~sc%random%.tmp
~zlp\zdf_%random%.data
~lcf\tfl_%random%

----

=== Registry keys and values
==== RC2FM
----
[HKEY_CURRENT_USER\Software\Microsoft\IE\Cache]
"Index"
----
==== RC2CL
----
[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Console]
or [HKEY_CURRENT_USER\Software\Microsoft\Direct3D]
"Settings"
"Type"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\OLE]
or [HKEY_CURRENT_USER\Software\Microsoft\Direct3D]
"Common"
"Current"
"ENC"
"FFLT"
"Flag1"
"FlagLF"
"FlagLF2"
"IfData"
"INFO"
"InstallA"
"InstallB"
"LegacyImpersonationNumber"
"LM"
"MachineAccessStateData"
"MachineState 0"
"RPT"
"SP2"
"SP3"
"SettingsMC"
"SettingsSR1"
"SettingsSR2"
----

=== C&C servers
==== Domain names

----
activationstate.sytes[.]net
advstatecheck.sytes[.]net
akamai.sytes[.]net
statbfnl.sytes[.]net
updchecking.sytes[.]net
----

==== IP addresses

[options="header"]
|=====
| Active period  | IP address
| 2013-2014      | `46.165.231.85`
| 2013-2014      | `213.239.220.41`
| 2014-2017      | `46.165.241.129`
| 2014-2016      | `46.165.241.153`
| 2014-2018      | `78.46.35.74`
| 2016-2016      | `95.215.111.109`
| 2016-2018      | `185.118.66.163`
| 2017-2017      | `185.118.67.233`
| 2017-2018      | `185.156.173.92`
| 2018-2018      | `46.165.230.241`
| 2018-2018      | `194.187.249.157`
|=====



== InvisiMole 2020 - Indicators of Compromise

The white paper about InvisiMole is available on WeLiveSecurity at
https://www.welivesecurity.com/wp-content/uploads/2020/06/ESET_InvisiMole.pdf.

A high level summary is also available as a blog post on WeLiveSecurity at
https://www.welivesecurity.com/2020/06/18/digging-up-invisimole-hidden-arsenal/.

=== ESET detection names

- Win32/InvisiMole
- Win64/InvisiMole

=== SHA-1 hashes

==== Trojanized applications

----
125FCA6EBD82682E51364CF93C9FFA8EB4F6CA5F
3B923FA1E5DCB4F65DAA138BECEB123D7C431D1B
3BB2C05DEA077835A79499A0BB81410D27EEBFAF
4C13AD9AD9C134DE15F3AE5E2F0D2EC1E290DEE8
728386C6D6EAF43148FE25F86E6AF248019D9842
793F4DD2B765ECD962A053246646ED0D6144D249
8147E85E13B3624FA290F1F218647A0D1FD70204
8C5F463FA79601DE38D0A77808226B1A8E67459A
9B1E0A22DEB124FF36FCF7ED2EA82E799B49B070
9B48090704C3F62D6B768780845E2D04862F5219
CD3419B4B3958BE5BE1CAEA60A4EE98E4D427A6D
D5D3A01A5944D55E5DDF1F915E88043691BE6F58
D8EB2429253E82729F34373068EC350D1B2DA8AB
DDB871AD5823BE31F5176F2B0CE149D4B6E44F24
E936E857A812690178ED049FD4A1766E281B9F1D
----

==== Loaders

----
09821EB9F2B79501B3928FBA2F313C723FEBB1B3
16E9B0ADBD53849E7F3A04FA8A5BF78E73A86841
21F320DEBDD4D97FA5420AF31A55FBC77B923819
240C8157E5E053B70C4D301D852C609C212F85F3
32A9FF262649623CBFF4C6B29BD8ED7F803E75E3
3EF0D0278DB40F6116645B0B915D56374EB77004
42086128F7213931D438BF127CC61D3F9483014A
4BBED6E307D214CAB9AE395E1F49104446B54D5A
55F6185AD64997756ADF03BC2D4CC4ABF5C64E4E
652991303B319F5DE440C18A0F14DF65B82265FB
66F9EA8017CD899AB146DED2E341201B51A9CE9F
6A6D956A8108E0D5339751927D5576369C0E2C34
6C49BF35116A147C7F3C5CE15ABA041F272E60B5
6DECBFCA132364CBD66DD07118959BCE95F83168
6DEF96407F52B3C82D665B2C6A9B230B3D080CD1
7901AD25A3673AC9CB1B6AE1FC9DC57A4B53383E
7BA31B83B2ADF7A9B43C56F4882D217512F333AF
82D653D71DC024C19894C2B2207D6C3414CA1B01
96D5E7C32AC299770E11DF521F867538361D9A8B
A27BB3E5F1CF56C89E5F9816CF8C5796D2FBB09E
A419F091723A5632DA85B0930F3B260599672C00
A527B41D60028BE24BE8CAC69DE9445401F280CD
A695FA12F97971A065FED927A30278C94C78C722
B1B3E88494F7C27354E68D83E16EB65BBEFC7FB3
B7712BBE5DE4386BAB11F61F1731C358648DECE6
BFEF295D375A60A2EEFE416709DE73F14AC1416C
CC595AAE9573BEEF92DE12C3DE9C85F7E9E1CD6D
DBEA8DAF48CC54C7CFB0DCC689D4C9549D3DD23F
DE6D8B66BE01934D672C04E92EA2EDC0210BF00E
E0B9C24DD5620FF70CB80002A4A772E16EB331F2
E489C4D6CA1DAFA034F7FADBF27DEEB202189833
F7EF9A3501EEBCFFA4615CC3BD473F65A203A1D6
FB4401DEA8911BEAB788E87A576EF5568DA82ED5
----

==== TCP downloader variations

----
02F4242F7CA7289C8EDFA7B4F465C62C7A6815E2
303A63CE12AD42900DA257428E2FD4DE4F9829DC
DBD21EF03CCC3A985D808B0C5EC7AC54DED5D1C9
2E7F737CAEB56716ACE36FADEB74EE610705283F
4B8E11E0734D3109627FF8871EF7DB14C0DE9C41
----

==== DNS downloader

----
31FAE273942A1E432DE91400F5D625F88101B966
5F09DF19232E0A77495EEDB1B715D9EF0B909634
E9AF42C4CF0299EEA7B405F9E3E925BCAFAB9F2B
F67300541D769C5AA071C766198F0B7E25476B23
F8CAA729C28EF6B0EC8AA74399CE4EE7A59B895C
----

==== RC2CL backdoor

----
00EA86AAB3D616A24A5E13D592FABC26416DFDBD
094DAEA5B97C510A8E9CFE3585B39B78522A2C61
0AAB85DDD4E25ADD24E9ECD83C8DD635B3A7C2F3
0B57CD2393E29084D545300D1749AA50EB23A8AB
11EBA9E198C458A8D86D70BD64B3FDB0163A38C4
20FF1A290A53B39C4E54A670E8C27852BE8BCFF4
554AA9A39CC241AAD5FBDC5FD39CECCB1EB9E7D0
7114B2E031D8853434028D39873338C33CE67C16
A1FFFB96415CF4146B056C9A847DC6EECD882DBB
AF67F640F33D1A46719056B66F45B91B2D56910A
FFB74AF734453973FED6663C16FB001D563FAF1C
----

==== RC2FM backdoor

----
27FC1DCB1B3DCA3E496F799A2944E4FB070AF39C
E1599FB73DDE78531BBF65063F10F239AEF29D70
E3BF27F1303BFDB877D1699D5B480342A9A2FE58
----

==== RC2FM helper DLL

----
7FE30CA69E6631CB9333C37F72E3CABBE8CE366C
----

==== Delivery chain (batch scripts)

----
6F98B12C98DA1FCFF078256970E9B8EF12139640
76FC2E29524C6AD58B0AF05251C419BB942CCED0
----

==== Control Panel misuse chain (Stage 2)

----
2402765EA67E04F151D32BF2B749B150BBD3993E
----

==== Control Panel misuse chain (Stage 4)

----
9F64FEC50D4447175459AAB33BC9126F9A3370D8
A3AFF8CE55907DAA1F3360DED01BCF3F6F9D0CF2
----

==== SMInit exploit chain (exploit)

----
E85D7F0564771C9396FDCDB9877DB0FF61C1D515
----

==== Speedfan exploit chain (Stage 4)

----
10C548992567A04DA199D09E3CA4B0C47B7A136C
----

==== Speedfan exploit chain (Stage 6)

----
B988F107E5F20CDC424EC9F470D157435FC03966
----

==== Wdigest exploit chain (Stage 3)

----
B894F320569286B56F4272D0CBBA4DB10C645AE0
----

==== Wdigest exploit chain (Stage 4)

----
66B7DB6E755EC648AEE210F163655A5662562DEE
7E8B99968C59FDE046DF3ECECED6049E4DFA7225
81BD3140F222FAC2DC6610E0CE79EDF34B599D47
9A3E870B61C4F37514F6E3E3FAB4D4506D3B50DB
AA5E8E21C79B0B4A02726233B9F5EB4994C87AD3
----

==== Wdigest exploit chain (Stage 5)

----
A42FA8FB11DA669124AC7968838427BF8E998872
D8B101B588DA6DA3CBE3E161C91986E64D6DD290
----


=== File names and paths

==== Delivery chain

----
api64.cmd
intel_log64.cmd
intel_log64.exe
----

==== EternalBlue exploit chain

----
stg0D0CE03.dll
stg0D33E0A.dll
----

==== Control Panel misuse chain

----
%APPDATA%\Control\Control.js
%APPDATA%\Microsoft\AddIns\imageapplet.dat
%APPDATA%\Microsoft\AddIns\infocardadd.cpl
%STARTUP%\Control Panel.lnk
----

==== SMInit exploit chain

----
%USERPROFILE%\AppData\Roaming\Microsoft\Sessions\hskin.dll
%USERPROFILE%\AppData\Roaming\Microsoft\Sessions\Settings.ini
%USERPROFILE%\AppData\Roaming\Microsoft\Sessions\SMInit.exe
%USERPROFILE%\AppData\Roaming\Microsoft\Sessions\TVPSkin.dll
----

==== Speedfan exploit chain

----
C:\Windows\system32\drivers\NGEN Framework\NGEN.cab
C:\Windows\system32\drivers\NGEN Framework\NGEN.exe
C:\Windows\system32\mscorscvs.exe
----

==== Wdigest exploit chain

----
%APPDATA%\Microsoft\Installer\kb043921.exe
%WINDIR%\SysWOW64\drivers\Rundll32.exe
%WINDIR%\SysWOW64\drivers\wdigest.dll
%WINDIR%\SysWOW64\wbem\setupSNK.exe
----

==== InvisiMole loaders

----
NlsModels0019.dll
NLSModels0022.dll
osppc.dll
osppcext.dll
WptsExtensions.dll
----

==== RC2FM backdoor

----
%APPDATA%\Microsoft\Internet Explorer\Cache\0IOQ61KI
%APPDATA%\Microsoft\Internet Explorer\Cache\4AINFWUJ
%APPDATA%\Microsoft\Internet Explorer\Cache\6FFT03MB
%APPDATA%\Microsoft\Internet Explorer\Cache\74BWF9JV
%APPDATA%\Microsoft\Internet Explorer\Cache\7KWRPZWK
%APPDATA%\Microsoft\Internet Explorer\Cache\AMB6HER8
%APPDATA%\Microsoft\Internet Explorer\Cache\CZPOL9V4
%APPDATA%\Microsoft\Internet Explorer\Cache\KQP70AQV
%APPDATA%\Microsoft\Internet Explorer\Cache\MX0ROSB1
%APPDATA%\Microsoft\Internet Explorer\Cache\NI8NKODB
%APPDATA%\Microsoft\Internet Explorer\Cache\OUB1N96O
%APPDATA%\Microsoft\Internet Explorer\Cache\V2JMDODG
%APPDATA%\Microsoft\Internet Explorer\Cache\W9U2CJ6T
%APPDATA%\Microsoft\Internet Explorer\Cache\Y68JG1TH
%APPDATA%\Microsoft\Windows\Iconcache.db
%APPDATA%Realtek\Drivers\Drv7\DP_Sound_Realtek_wnt\A6305_WDM\alcrmv.exe
%TEMP%\~log
%TEMP%\vsfilter_%random%.dll
----

=== Registry keys/values

==== Control Panel misuse chain

----
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Control Panel\CPLs]
"infocard" = %APPDATA%\Microsoft\AddIns\infocardadd.cpl
----

==== Speedfan exploit chain

----
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\services\clr_optimization_v2.0.51527_X86]
"Type"=dword:00000010
"Start"=dword:00000002
"ErrorControl"=dword:00000000
"ImagePath"= "C:\Windows\system32\mscorscvs.exe"
"DisplayName"="Microsoft .NET Framework NGEN v2.0.51527_X86"
"ObjectName"="LocalSystem"
"Description"="Microsoft .NET Framework NGEN v.2"

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\services\clr_optimization_v2.0.51527_X86\Parameters]
"Application"="C:\Windows\system32\drivers\NGEN Framework\NGEN.exe"
"AppDirectory"="C:\Windows\system32\drivers\NGEN Framework"
"AppParameters"="VirtualAlloc 0 0x20000 0x3000 0x40 , CreateFileW "Ngen.cab" 0x80000000 0 0 3 0 0 , SetFilePointer $$:7 64 0 0 , ReadFile $$:7 $$:1 0x20000 $b:4 0 , CloseHandle $$:7 , EnumUILanguagesA $$:1 4 $$:1"

[HKEY_LOCAL_MACHINE\software\microsoft\drm] or [HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion] or [HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\ext] or [HKEY_LOCAL_MACHINE\software\microsoft\function discovery\registrystore\publication\explorer]
"1Extylc8fC5X1PL"
"1Extylc8fC5X1HK"
"1Extylc8fC5X1RK"
"1Extylc8fC5X2PL"
"1Extylc8fC5X2HK"
"1Extylc8fC5X2RK"
"1Extylc8fC5X3PL"
"1Extylc8fC5X3HK"
"1Extylc8fC5X3RK"
----

==== Wdigest exploit chain

----
[HKEY_CURRENT_USER\SOFTWARE\Classes\lnkfile]
"Curver" = ".zeros"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ms-settings]
"Curver" = ".zeros"

[HKEY_CURRENT_USER\SOFTWARE\Classes\.zeros\shell\open]
"command" = ""%APPDATA%\Microsoft\Installer\kb043921.exe" OpenFileMappingW 0xF003F 0 "XVD21x9DC" , MapViewOfFile $$:1 0xF003F 0 0 %installer_size% , CreateThread 0 0 $$:6 $$:6 0 0 , WaitForSingleObject $$:13 -1"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\FlashConfig] or [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\FlashConfig]
"FlashConfigEnrollee" = "shell32 ShellExec_RunDLL  "C:\Windows\SysWOW64\drivers\Rundll32.exe" "C:\Windows\SysWOW64\drivers\wdigest.dll",SpInitialize %SHELLCODE_BYTES%"

[HKEY_LOCAL_MACHINE\SOFTWARE\ODBC] or [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ODBC]
"A"
"B"
"C"
"D"
"M"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CsPower]
"Type"=dword:00000020
"Start"=dword:00000004
"ErrorControl"=dword:00000000
"ImagePath"= "%SystemRoot%\System32\svchost.exe -k DComLaunch" (translated from hex)
"DisplayName"="System Group"
"Group"="Plugplay"
"ObjectName"="LocalSystem"
"RequiredPrivileges"=SeTcbPrivilege
SeSecurityPrivilege
SeAssignPrimaryTokenPrivilege
SeTakeOwnershipPrivilege
SeLoadDriverPrivilege
SeBackupPrivilege
SeRestorePrivilege
SeImpersonatePrivilege
SeAuditPrivilege
SeChangeNotifyPrivilege
SeUndockPrivilege
SeDebugPrivilege
SeSystemEnvironmentPrivilege (translated from hex)
"DeleteFlag"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CsPower\Parameters]
"ServiceDll"= "%SystemRoot%\System32\FXSCOMPOSE.dll" (translated from hex)
"ServiceMain"="HrSelectEmailRecipient"
----

==== DNS downloader

----
[HKEY_CURRENT_USER\Software\Microsoft\EventSystem]
"AutoExA"
"AutoExB"
"AutoExC"

[HKEY_CURRENT_USER\Software\Microsoft\EventSystem]
"KeyA"
"KeyB"
"KeyC"
----

==== RC2FM backdoor

----
[HKEY_CURRENT_USER\Software\Microsoft\IE\Cache]
"Index"

[HKEY_CURRENT_USER\Software\Microsoft\IE]
"SecureProtocols"

[HKEY_CURRENT_USER\Software\Microsoft\IE\Thumbnails]
----

==== RC2CL backdoor

----
[HKEY_CURRENT_USER\Software\Microsoft\Direct3D] or [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Console]
"BSKS"
"Common"
"Current"
"DisableFM"
"Edit"
"ENC"
"ENCEx"
"ENCEx2"
"FFLT"
"Flag1"
"FlagLF"
"FlagLF2"
"IfData"
"INFO"
"InstallA"
"InstallB"
"LastFD"
"LegacyImpersonationNumber"
"LM"
"MachineAccessStateData"
"MachineAT"
"MachineDataUM"
"MachineNW"
"MachineState 0"
"MFLT"
"OverMin"
"RPT"
"SettingsFM"
"SettingsMC"
"SettingsSR1"
"SettingsSR2"
"SP2"
"SP3"
"UseDFlag"

(Unknown registry key)
"Value_Bck"
"Value_Cmnm"
"Value_CMS"
"Value_DFl"
"Value_DFM"
"Value_FAT"
"Value_FGL"
"Value_FPP_ZC"
"Value_LastL"
"Value_LgsD"
"Value_LM"
"Value_LNM"
"Value_LsFl1"
"Value_LsFl2"
"Value_M1"
"Value_MD"
"Value_MF"
"Value_MFV"
"Value_MIN"
"Value_MMc"
"Value_MNL"
"Value_MRP"
"Value_MSS"
"Value_onFPL"
"Value_OvMin"
"Value_PEIP_ZC"
"Value_PtS"
"Value_SlF"
"Value_SR1"
"Value_SR2"
"Value_SRC"
"Value_uLA"
"Value_uLB"
"Value_Ulcf"
"Value_UM"
"Value_WDSP_ZC"
"Value_WPDF_ZC"
"Value_WSFX_ZC"
----

=== Synchronization objects

==== Mutex names
* `MSO~2`
* `MSO~4`
* `Mutex_sync`
* `wkssvmtx`

==== Semaphore names
* `Global\BrLK`
* `Global\GtLK`
* `Global\M6Br`
* `Global\M6Gt`
* `Global\M6Nx`
* `Global\M6St`
* `Global\MBrT`
* `Global\MMGt`
* `Global\MMNx`
* `Global\MMSt`
* `Global\NxLK`
* `Global\StLK`
* `Global\TsLK`
* `Global\TsM5`
* `Global\TsM6`

==== Shared memory names
* `ExMp0043`
* `ExMp0044`
* `XVD21x9DC`

==== Event names
* `EvMExM2ER`
* `EvMExM2OK`
* `ExMpER43`
* `ExMpER44`
* `ExMpOK43`
* `ExMpOK44`

=== C&C servers

==== IP addresses
* `46.165.220[.]228`
* `80.255.3[.]66`
* `85.17.26[.]174`
* `185.193.38[.]55`
* `194.187.249[.]157`
* `195.154.255[.]211`

==== Domain names
* `153[.]re`
* `adstat[.]red`
* `adtrax[.]net`
* `akamai.sytes[.]net`
* `amz-eu401[.]com`
* `blabla234342.sytes[.]net`
* `mx1[.]be`
* `statad[.]de`
* `time.servehttp[.]com`
* `upd[.]re`
* `update[.]xn--6frz82g`
* `updatecloud.sytes[.]net`
* `updchecking.sytes[.]net`
* `wlsts[.]net`
