:toc:
:toclevels: 2

= Dukes Indicators of Compromise

== Operation Ghost Indicators of Compromise

The white paper about Operation Ghost is available on WeLiveSecurity at https://www.welivesecurity.com/wp-content/uploads/2019/10/ESET_Operation_Ghost_Dukes.pdf.
A high level summary is also available as a blog post on WeLiveSecurity at https://www.welivesecurity.com/2019/10/17/operation-ghost-dukes-never-left/.

The https://www.misp-project.org[MISP] event is available in link:misp-dukes-operation-ghost-event.json[`misp-dukes-operation-ghost-event.json`].

=== Sample hashes

[options="header"]
|========================================
|SHA-1 hash|Component|Compilation Time (GMT)|ESET Detection Name
|`4BA559C403FF3F5CC2571AE0961EAFF6CF0A50F6`|PolyglotDuke|07/07/2014|Win32/Agent.ZWH
|`CF14AC569A63DF214128F375C12D90E535770395`|PolyglotDuke|07/06/2017|Win32/Agent.AAPY
|`539D021CD17D901539A5E1132ECAAB7164ED5DB5`|PolyglotDuke|07/06/2017|Win32/Agent.ZWH
|`0E25EE58B119DD48B7C9931879294AC3FC433F50`|PolyglotDuke|07/08/2017|Win64/Agent.OL
|`D625C7CE9DC7E56A29EC9A81650280EDC6189616`|PolyglotDuke|19/10/2018|Win64/Agent.OL
|`0A5A7DD4AD0F2E50F3577F8D43A4C55DDC1D80CF`|RegDuke Loader|21/12/2017|MSIL/Tiny.BG
|`F7FD63C0534D2F717FD5325D4397597C9EE4065F`|RegDuke Loader|10/07/2018|MSIL/Tiny.BG
|`194D8E2AE4C723CE5FE11C4D9CFEFBBA32DCF766`|RegDuke Loader|29/08/2018|MSIL/Agent.TGC
|`64D6C11FFF2C2AADAACEE01B294AFCC751316176`|RegDuke Loader|01/10/2018|MSIL/Agent.SVP
|`6ACC0B1230303F8CF46152697D3036D69EA5A849`|RegDuke Loader|25/10/2018|MSIL/Agent.SXO
|`170BE45669026F3C1FC5BA2D48817DBF950DA3F6`|RegDuke Loader|01/12/2018|MSIL/Agent.SYC
|`5905C55189C683BC37258AEC28E916C41948CD1C`|RegDuke backdoor|29/08/2018|MSIL/Agent.CAW
|`B05CABA461000C6EBD8B237F318577E9BCCD6047`|MiniDuke|17/08/2018|Win32/Agent.TSG
|`718C2CE6170D6CA505297B41DE072D8D3B873456`|MiniDuke|24/06/2019|Win32/Agent.TUF
|`A88DA2DD033775F7ABC8D6FB3AD5DD48EFBEADE1`|FatDuke|03/05/2017|Win32/Agent.TSH
|`DB19171B239EF6DE8E83B2926EADC652E74A5AFA`|FatDuke|22/05/2019|Win32/Agent.TSH
|`9E96B00E9F7EB94A944269108B9E02D97142EEDC`|FatDuke Loader|19/04/2019|Win32/Agent.AAPY
|`AF2B46D4371CE632E2669FEA1959EE8AF4EC39CE`|LiteDuke|02/10/2014|Win32/Agent.AART
|========================================

=== Network

==== PolyglotDuke

===== Public Webpages
----
http://ibb[.]co/hVhaAq
http://imgur[.]com/1RzfF7r
http://imgur[.]com/6wjspWp
http://imgur[.]com/d4ObKL0
http://imgur[.]com/D6U06Ci
http://imgur[.]com/GZSK9zI
http://imgur[.]com/wcMk7a2
http://imgur[.]com/WMTwSMJ
http://imgur[.]com/WOKHonk
http://imgur[.]com/XFa7Ee1
http://jack998899jack.imgbb[.]com
http://simp[.]ly/publish/pBn8Jt
http://thinkery[.]me/billywilliams/5a0170161cb602262f000d2c
http://twitter[.]com/aimeefleming25
http://twitter[.]com/hen_rivero
http://twitter[.]com/JamesScott1990
http://twitter[.]com/KarimM_traveler
http://twitter[.]com/lerg5pvo1i
http://twitter[.]com/m63vhd7ach3
http://twitter[.]com/MarlinTarin
http://twitter[.]com/np8j7ovqdl
http://twitter[.]com/q5euqysfu5
http://twitter[.]com/qistp743li
http://twitter[.]com/t8t842io2
http://twitter[.]com/ua6ivyxkfv
http://twitter[.]com/utyi5asko02
http://twitter[.]com/vgmmmyqaq
http://twitter[.]com/vvwc63tgz
http://twitter[.]com/wekcddkg2ra
http://twitter[.]com/xzg3a2e2z
http://www.evernote[.]com/shard/s675/sh/6686ff4e-8896-499b-8cdb-a2bbf2cc4db9/fc7fbe66c820f17c30147235e95d31b8
http://www.fotolog[.]com/g1h4wuiz6
http://www.fotolog[.]com/gf3z425rr0
http://www.fotolog[.]com/i4ntff47xfw
http://www.fotolog[.]com/joannevil/121000000000030009/
http://www.fotolog[.]com/o2rh2s2x7pu
http://www.fotolog[.]com/q4tusizx9xb
http://www.fotolog[.]com/rypnil03sl6
http://www.fotolog[.]com/shx8hypubt
http://www.fotolog[.]com/u99aliw5g
http://www.fotolog[.]com/uq44y4j19m8
http://www.fotolog[.]com/vq21p34
http://www.fotolog[.]com/vz1g3wmwu
http://www.fotolog[.]com/zu2of5vyfl6
http://www.google[.]com/?gws_rd=ssl#q=Heiofjskghwe+Hjwefkbqw
http://www.kiwibox[.]com/AfricanRugby/info/
http://www.kiwibox[.]com/GaryPhotographe/info/
http://www.reddit[.]com/user/BeaumontV/
http://www.reddit[.]com/user/StevensThomasWis/
----

===== C&C domains

----
acciaio.com[.]br
ceycarb[.]com
coachandcook[.]at
fisioterapiabb[.]it
lorriratzlaff[.]com
mavin21c.dothome.co[.]kr
motherlodebulldogclub[.]com
powerpolymerindustry[.]com
publiccouncil[.]org
rulourialuminiu.co[.]uk
sistemikan[.]com
varuhusmc[.]org
----

==== MiniDuke

----
ecolesndmessines[.]org
salesappliances[.]com
----

==== FatDuke

----
busseylawoffice[.]com
fairfieldsch[.]org
ministernetwork[.]org
skagenyoga[.]com
westmedicalgroup[.]net
----

==== LiteDuke

----
bandabonga[.]fr
----
