:toc:

= SparklingGoblin Indicators of Compromise

== You never walk alone: the SideWalk backdoor gets a Linux variant

The blog post on SideWalk Linux is available on
https://www.welivesecurity.com/2022/09/14/you-never-walk-alone-sidewalk-backdoor-linux-variant/[WeLiveSecurity].

=== Files

[options="header"]
|===
|SHA-1 |Filename |Detection |Description
|`FA6A40D3FC5CD4D975A01E298179A0B36AA02D4E` |ssh_tunnel1_0  |Linux/SideWalk.L |SideWalk Linux (StageClient variant)
|`7DF0BE2774B17F672B96860D013A933E97862E6C` |hw_ex_watchdog |Linux/SideWalk.B |SideWalk Linux (Specter variant)
|===

=== Network IOCs

[options="header"]
|===
|Domain |IP |First seen |Details
|`rec.micosoft[.]ga` |`172.67.8[.]59`   |2021-06-15 |SideWalk C&C server (StageClient variant)
|                    |`66.42.103[.]222` |2020-09-25 |SideWalk C&C server (Specter variant)
|===

=== MITRE ATT&CK matrix

[options="header"]
|=====
|ID       |Name
|T1587.001 |Develop Capabilities: Malware
|T1016 |System Network Configuration Discovery
|T1071.001 |Application Layer Protocol: Web Protocols
|T1573.001 |Encrypted Channel: Symmetric Cryptography
|=====

== The SideWalk may be as dangerous as the CROSSWALK

An analysis of SideWalk is available as a https://www.welivesecurity.com/2021/08/24/sidewalk-may-be-as-dangerous-as-crosswalk/[blogpost on WeLiveSecurity].

=== ESET detection names

- MSIL/ShellcodeRunner.L.gen
- Win64/Agent.AQD
- MSIL/ShellcodeRunner.O

=== SHA-1 hashes

==== Loaders

===== InstallUtil-based .NET loader used to decrypt and load SideWalk

----
1077A3DC0D9CCFBB73BD9F2E6B72BC67ADDCF2AB
----

===== ChaCha20-based shellcode loader used to decrypt and load the SideWalk shellcode

----
153B8E46458BD65A68A89D258997E314FEF72181
----

===== InstallUtil-based .NET loader used to decrypt and load Cobalt Strike

----
EA44E9FBDBE5906A7FC469A988D83587E8E4B20D
----

==== Payloads

===== Cobalt Strike encrypted shellcode

----
AA5B5F24BDFB049EF51BBB6246CB56CEC89752BF
----

===== SideWalk ChaCha20-encrypted shellcode

----
829AADBDE42DF14CE8ED06AC02AD697A6C9798FE
----

===== SideWalk decrypted shellcode

----
9762BC1C4CB04FE8EAEEF50A4378A8D188D85360
----

=== IP addresses

- `++104.21.49[.]220++`
- `++80.85.155[.]80++`
- `++193.38.54[.]110++`

=== Domain names

- `++update.facebookint.workers[.]dev++`
- `++cdn.cloudfiare.workers[.]dev++`

=== File names

- `C:\Windows\System32\Tasks\Microsoft\Windows\WindowsUpdate\WebService`
- `C:\windows\system32\tasks\Microsoft\Windows\Ras\RasTaskStart`
- `iislog.tmp`
- `mscorsecimpl.tlb`
- `C_25749.NLS`
- `Microsoft.WebService.targets`

=== Digital Certificate

----
Serial number: 8E812FCAD3B3855DFD78980CEE0BEB71
Thumbprint: D54AEB62D0102D0CC4B96CA9E5EAADE3846EC470
CN = CloudFlare Origin Certificate
O = CloudFlare, Inc.
L = San Francisco
S = California
C = US
Valid from: 2020-11-04 09:35:00
Valid to: 2035-11-01 09:35:00

-----BEGIN CERTIFICATE-----
MIIEqjCCA5KgAwIBAgIUWrynbo6BL8rTs4Vd/XiYDO4L63EwDQYJKoZIhvcNAQEL
BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MB4XDTIwMTEwNDA5MzUwMFoXDTM1MTEwMTA5MzUwMFowYjEZMBcGA1UEChMQQ2xv
dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvtgUHtVesPyv6HuZ/nlUGSL4Z5UgI95uwSSj
7BS6a/vSGXWaKQ+JgZC+wd1VUV8B+dd5b0Jvpoz7U0uxycp3Ixywhm/0hT9rJUpr
CtJLID1dIcXYcib2K7OWXeptOJ2Ev0b/wlB9v+EzA8819m+mVI6mZCQOJQGafeqg
yDZ8Zcd2IYWB/6mbpyFkY5pWWECIzREhiF93fh6SevFOckutMdklvcvassRy2S2W
7XEov4rw4r+Im92QgW10lQlwKssGu/ZhJgKW0ByagKSrDTWYzJSJJZYJuPFhf7Bv
0Y7pxrc9HQXMFXHyyoV+v/5DuI+5MP3cKPxF8SvSM8HvBtPwQwIDAQABo4IBLDCC
ASgwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBT/SVFFIMk1KOqwjCgCDpznAgk10TAf
BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
YTAtBgNVHREEJjAkghEqLmZhY2Vib29raW50LmNvbYIPZmFjZWJvb2tpbnQuY29t
MDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6Ly9jcmwuY2xvdWRmbGFyZS5jb20vb3Jp
Z2luX2NhLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAVdFTWiTbnKYHiOk1IjNP+Lm1
I7f3916HiavNdo/VV5lL2/4CdVw3QcZaHYq2VNWQy2AyyUclIsSehJCXrpDphhCm
sj18yCfqG9pSqSVt8F62fPRwLb/W/zLSe7MXb+FvYih/G7sxAm/1KnlojMaXPPyY
NhBeR4Cedam1C5KOCahd7gzIfd5y5OsU7KOiOC6yvOHZcFHCV1nhUrGCyrsnd8Dy
26aTPU0R6FgIWBmoWIKLHW18mR6EX/wjqLGcSAQNtsxrxU5SNWdjVR69L5BHwouv
Jydp37vBYjlDIeGmWFfbi7DMnDhA470tDzMmGZnrLnE9n0ok7tkdZh84iLRyLg==
-----END CERTIFICATE-----
----

=== MITRE ATT&CK matrix

[options="header"]
|=====
|ID       |Name
|T1583.001|Acquire Infrastructure: Domains
|T1583.004|Acquire Infrastructure: Server
|T1583.006|Acquire Infrastructure: Web Services
|T1587.001|Develop Capabilities: Malware
|T1587.003|Develop Capabilities: Digital Certificates
|T1053.005|Scheduled Task/Job: Scheduled Task
|T1574.001|Hijack Execution Flow: DLL Search Order Hijacking
|T1053.005|Scheduled Task/Job: Scheduled Task
|T1134.001|Access Token Manipulation: Token Impersonation/Theft
|T1140|Deobfuscate/Decode Files or Information
|T1055.012|Process Injection: Process Hollowing
|T1218.004|Signed Binary Proxy Execution: InstallUtil
|T1012|Query Registry
|T1082|System Information Discovery
|T1016|System Network Configuration Discovery
|T1071.001|Application Layer Protocol: Web Protocols
|T1573.001|Encrypted Channel: Symmetric Cryptography
|T1008|Fallback Channels
|T1090|Proxy
|T1102|Web Service
|T1102.001|Web Service: Dead Drop Resolver
|=====
