= Linux/Moose Indicators of Compromise (IOC)
:vt-url: https://www.virustotal.com/latest-scan/

// Olivier Bilodeau <bilodeau@eset.com>
// Copyright (C) 2015 ESET

These IOCs were released as part of our research on this embedded Linux
threat. The full report is available here:
http://www.welivesecurity.com/wp-content/uploads/2015/05/Dissecting-LinuxMoose.pdf

We have other resources related to this threat available in
https://github.com/eset/malware-research/tree/master/moose[our
malware-research repository]:

We have IOCs in the form of Hashes, IP addresses, Yara rules and system
commands. Hashes, IP addresses and systems commands are documented here, the
rest is in separate files inside this folder.

////
We would like to thank http://www.emergingthreats.net/[Emerging Threats] for
their help in improving the Snort rules provided here.
////

CAUTION: As soon as this information is public the malware authors will most
         likely update their technique and tools to evade detection and thwart
         analysis as they have done in the past. Consequently, be aware that
         any of the advice we give to identify or clean oneself might already
         be outdated.

WARNING: These come with no warranties. They might not detect an infection
         and/or trigger false positives. Apply judgment.

If you find false-positives, have improved IOCs or find samples that do not
match these IOCs please open an issue, provide a pull-request or contact us
at: github@eset.com.

== Malware samples

Here are the SHA1 hashes, architecture and malware version of the files we've encountered:

.Malware Samples
[options="header"]
|=====================================================================================================================
|File Hash                                                                                 |Architecture/ABI | Version
|{vt-url}10e2f7dd4b2bb4ac9ab2b0d136f48e5dc9acc451[10e2f7dd4b2bb4ac9ab2b0d136f48e5dc9acc451]| ARM GNU EABI    | 20
|{vt-url}095ee85aa648de4e557fc243de17d4f00ab2091f[095ee85aa648de4e557fc243de17d4f00ab2091f]| ARM GNU EABI    | 20
|{vt-url}bfc2a99450977dc7ba2ec0879fb17c612e248ece[bfc2a99450977dc7ba2ec0879fb17c612e248ece]| MIPS MIPS32     | 28
|{vt-url}54041ce90b04698465b866ed169ddf4a269e1e76[54041ce90b04698465b866ed169ddf4a269e1e76]| MIPS MIPS32 LSB | 28
|{vt-url}d648c405507ad62ddb3faa1dd37f659f3676cacf[d648c405507ad62ddb3faa1dd37f659f3676cacf]| ARM EABI5       | 28
|{vt-url}85c3439b6773241d11cda78f0ecfea4c07e55fd2[85c3439b6773241d11cda78f0ecfea4c07e55fd2]| ARM EABI5       | 28
|{vt-url}216014dba6f1a636c44530fbce06c598d3cf7fa1[216014dba6f1a636c44530fbce06c598d3cf7fa1]| ARM EABI5       | 29
|{vt-url}4bffc0ebfe8c373f387eb01a7c5e2835ec8e8757[4bffc0ebfe8c373f387eb01a7c5e2835ec8e8757]| MIPS MIPS32     | 29
|{vt-url}dd7e8211336aa02851f6c67690e2301b9c84bb26[dd7e8211336aa02851f6c67690e2301b9c84bb26]| MIPS MIPS32     | 31
|=====================================================================================================================

[appendix]
== IP Addresses

Traffic from infected device to these IP:ports combinations using TCP. These
are the primary C&C servers.

    77.247.177.36:81
    93.190.140.221:80
    85.159.237.107:81
    85.159.237.108:81
    77.247.177.87:81

Traffic from these IP addresses (from the whitelist) going to infected devices
on TCP port 10073.

    27.124.41.11
    27.124.41.31
    27.124.41.31
    27.124.41.33
    27.124.41.33
    27.124.41.52
    27.124.41.52
    42.119.173.138
    77.247.177.31
    77.247.177.36
    77.247.178.177
    79.176.26.142
    82.146.63.15
    85.159.237.107
    85.159.237.108
    85.159.237.111
    85.159.237.111
    93.190.139.123
    93.190.139.147
    93.190.140.221
    93.190.142.113
    93.190.143.60
    103.238.216.21
    103.238.216.216
    103.238.216.217
    103.238.216.218
    103.238.216.22
    103.238.216.23
    103.238.216.24
    103.238.216.25
    103.238.216.26
    103.238.216.28
    103.238.216.29
    103.238.216.30
    103.238.216.31
    109.201.148.136
    109.201.148.201
    109.201.148.241
    109.236.86.18
    109.236.89.208
    192.126.184.234
    207.244.67.193
    217.23.12.124
    217.23.2.249
    217.23.2.251
    217.23.2.252
    217.23.2.253
    217.23.2.30
    217.23.2.47
    217.23.2.48
    217.23.2.49
    217.23.2.52
    217.23.2.79
    217.23.7.133
    217.23.7.211

== System commands

You need shell access to your router. The malware obtains shell access by
leveraging weak or default usernames and passwords via the Telnet protocol. If
there is a custom text user interface (prompt not looking like `#`) on the
router then it tries to obtain a root shell by issuing `sh`.

Once you have a root shell access to your router. You can verify for the following
indicators:

* The presence of a binary named `elan2` in `/var` or `/dev` (or anywhere else)
* A process `elan2` running: `ps -ef | grep elan2`
* A process listening on 0.0.0.0:10073

This last indicator can be verified using `netstat -anp`. Depending on system
configuration the `-p` flag might not be available. If it's not, then you can
look for `lsof` or try manually correlating the content of `/proc/net/tcp/`
with `/proc/<pid>/fd` as
http://serverfault.com/questions/219984/busybox-netstat-no-p[explained here].

== Detection (YARA)

In order to identify if a file or a set of files is the Linux/Moose threat you
can use the popular http://plusvic.github.io/yara/[yara] tool.

Using the `linux-moose.yar` Yara rule in this repository you can recursively
crawl a directory for Linux/Moose with:

    yara -r linux-moose.yar directory/

If the command yields no output then no files were identified to be
Linux/Moose. Otherwise identified filenames are printed.

Further modifications made by the malware authors to evade detection will
impact the usefulness of this Yara rule over time.
