:toc:
:toclevels: 2

= Operation NightScout -- Indicators of Compromise

These are the IoCs from
https://www.welivesecurity.com/2021/02/01/operation-nightscout-supply-chain-attack-online-gaming-asia["Operation NightScout: Supply-chain attack targeting online gaming in Asia"]
blogpost.

== Samples

=== Malicious Update variant 1
|=====
|SHA1                                      |ESET Detection name
|`CA4276033A7CBDCCDE26105DEC911B215A1CE5CF`|Win32/Agent.UOJ
|=====

=== Malicious Update variant 2
|=====
|SHA1                                      |ESET Detection name
|`E45A5D9B03CFBE7EB2E90181756FDF0DD690C00C`|Win32/GenKryptik.ENAT
|=====

=== Malicious Update variant 3
|=====
|SHA1                                      |ESET Detection name
|`AA3D31A1A6FE6888E4B455DADDA4755A6D42BEEB`|Win32/Kryptik.HHBQ
|=====

=== Malicious Update variant 4
|=====
|SHA1                                      |ESET Detection name
|`5732126743640525680C1F9460E52D361ACF6BB0`|Win32/Delf.UOD
|=====

=== C&C domains
----
cdn.cloudistcdn[.]com
q.cloudistcdn[.]com
update.boshiamys[.]com
----

=== C&C IP addresses
----
210.209.72[.]180
103.255.177[.]138
185.239.226[.]172
45.158.32[.]65
----

=== Malicious update URLs
----
http://cdn.cloudfronter[.]com/player/upgrade/ext/20201030/1/35e3797508c555d5f5e19f721cf94700.exe
http://cdn.cloudfronter[.]com/player/upgrade/ext/20201101/1/bf571cb46afc144cab53bf940da88fe2.exe
http://cdn.cloudfronter[.]com/player/upgrade/ext/20201123/1/2ca0a5f57ada25657552b384cf33c5ec.exe
http://cdn.cloudfronter[.]com/player/upgrade/ext/20201225/7c21bb4e5c767da80ab1271d84cc026d.exe
http://cdn.cloudfronter[.]com/player/upgrade/ext/20210119/842497c20072fc9b92f2b18e1d690103.exe
https://cdn.cloudfronte[.]com/player/upgrade/ext/20201020/1/c697ad8c21ce7aca0a98e6bbd1b81dff.exe
http://cdn.cloudfronte[.]com/player/upgrade/ext/20201030/1/35e3797508c555d5f5e19f721cf94700.exe
http://res06.bignox[.]com/player/upgrade/202009/6c99c19d6da741af943a35016bb05b35.exe
http://res06.bignox[.]com/player/upgrade/202009/42af40f99512443cbee03d090658da64.exe
----

=== MITRE ATT&CK matrix
|=====
|ID       |Name
|T1195.002|Supply Chain Compromise: Compromise Software Supply Chain
|T1053.005|Scheduled Task/Job: Scheduled Task
|T1569.002|System Services: Service Execution
|T1574.002|Hijack Execution Flow: DLL Side-Loading
|T1090.001|Proxy: Internal Proxy
|T1140    |Deobfuscate/Decode Files or Information
|T1095    |Encrypted Channel
|T1056.001|Input Capture: Keylogging
|T1095    |Non-Application Layer Protocol
|T1041    |Exfiltration Over C2 Channel
|=====
