:toc:
:toclevels: 2

= Gamaredon -- Indicators of Compromise

== ESET detection names

- Win32/Pterodo
- Win64/Pterodo
- MSIL/Pterodo
- DOC/TrojanDownloader.Pterodo
- VBA/Pterodo
- JS/Pterodo
- LNK/TrojanDownloader.Pterodo
- PowerShell/Pterodo
- VBS/Pterodo
- Win32/TrojanDownloader.Pterodo

== Cyberespionage the Gamaredon way (2022/2023)

The whitepaper about Gamaredon is available on WeLiveSecurity at https://web-assets.esetstatic.com/wls/en/papers/white-papers/cyberespionage-gamaredon-way.pdf.

A high level summary is also available as a blog post on WeLiveSecurity at https://www.welivesecurity.com/en/eset-research/cyberespionage-gamaredon-way-analysis-toolset-used-spy-ukraine-2022-2023.

=== Sample Hashes

[options="header"]
|===
|SHA-1 |Detection |Description
|`+DF1C0A70E7A02B839AB3AAC3FC410E61EEFB58EB+` |VBS/Pterodo.AEV |PteroX - a VBScript general-purpose downloader.
|`+B50F10BBDB49BE6D868B09F3E1DD6C78D58D8E89+` |PowerShell/Pterodo.FR |PteroBleed - steals the IndexedDB database from various browsers.
|`+0879644944178645498E20EB4F59F2A8F128255D+` |PowerShell/Pterodo.GA |Downloader of PteroBleed.
|`+82123C17117EF235F3B57D0C5572C861E3ED7173+` |Win32/Pterodo.CEZ |PteroCDrop - dropper with various C or VBScript payloads.
|`+5720FFDF9D9CD649445CBC12844E2B587622643A+` |PowerShell/Pterodo.GC |PteroClone - uses rclone to download the next stage.
|`+55CD3FB7D1FDE869441154573C9C62D93E0570E0+` |PowerShell/Pterodo.GA |Downloader of PteroClone.
|`+F05874C1B908FDEF4B9AF2B084E3D813595A12C9+` |PowerShell/Pterodo.FY |PteroCookie - cookie stealer.
|`+CEA83C1AF6736484A172F7A3B876427CDF276473+` |PowerShell/Pterodo.GA |Downloader of PteroCookie.
|`+FEA57A486EB4BDAC5E7D59C9958C42293A5ABE12+` |VBS/Pterodo.AFA |PteroDash - a VBScript general-purpose downloader.
|`+1AEAE7A567C71200BA804801C4CEC227D2B64414+` |PowerShell/Pterodo.FF |PteroDig - LNK weaponizer.
|`+A3260C3314DF25DBF3369B7C516BD9D4C1B4B1E4+` |PowerShell/Pterodo.GK |Downloader of PteroDig.
|`+B2B58CEF19546B2D2284B2EB5F22B6D8FDB94D4E+` |VBS/Pterodo.VE |PteroDoc - Word document weaponizer.
|`+AC17FD08A3987CC91DFD6649BA3DABE8A9671305+` |PowerShell/Pterodo.FT |PteroGram - steals data that belongs to the Telegram Desktop application.
|`+945A50678E6E9AA293707E4F41E9BC81B9098BC5+` |PowerShell/TrojanDownloader.Agent.GBK |Downloader of PteroGram.
|`+AB7C5C7CD6F75B1D0A7AD29176A254055BE5356E+` |VBS/Pterodo.SC |Downloader of PowerShell version of PteroLNK.
|`+866E874CFF4EAD29889924AA02630E68AE252B55+` |VBS/Pterodo.SL |Downloader of the VBScript version of PteroLNK.
|`+49CF239AB2EBD04CAFDCEC07FBB0C1C1A43E8C02+` |PowerShell/Pterodo.FC |PowerShell version of PteroLNK - USB drive weaponizer.
|`+801A9B08987977692223B7105DEC8B21B9D9749E+` |PowerShell/Pterodo.GN |PowerShell version of PteroLNK - USB drive weaponizer.
|`+44C720AE508F448263A83CAC26775D6709DFBBDD+` |PowerShell/Pterodo.GN |PowerShell version of PteroLNK - USB drive weaponizer.
|`+E537DEAF3A77C5C0F0B9F8A12FF5995DD24CD259+` |PowerShell/Pterodo.GN |PowerShell version of PteroLNK - USB drive weaponizer.
|`+7793282401B134077E70217B55B0C4B45850D119+` |VBS/Pterodo.PS |VBScript version of PteroLNK - USB drive weaponizer.
|`+0FA9303ED739A3C6A76CEF4517B9ADB60C73CA80+` |PowerShell/Pterodo.JJ |Downloader of PteroPSDoor variant1.
|`+A3C21F9A493A05F9428E8F5FE5AF7F0C2BF67F95+` |PowerShell/Pterodo.GA |Downloader of PteroPSDoor variant2.
|`+821362A484908E93F8BA748B600665AE6444303D+` |Win32/Pterodo.BUD |PteroPSDoor variant1 version 7051.
|`+66049304E03AB624167B68501202A254E9ADD060+` |Win32/Pterodo.BUD |PteroPSDoor variant1 version 7052.
|`+BA5F7E2FA9BE1CB3FC7AE113F41C36E4F2C464B6+` |PowerShell/Pterodo.GS |PteroPSDoor variant1 version 7208.
|`+742E34BA21650ECB0B7EF33F786641F0BE823BE8+` |PowerShell/Pterodo.BY |PteroPSDoor variant2 version 7111.
|`+4F915541291120AA100123C1C93FA7DE78F46A3F+` |PowerShell/Agent.BGU |PteroPSLoad - PowerShell downloader.
|`+025E3D88C53FC12D5A4AAB726E696F2815BAC84D+` |VBS/Pterodo.TX |PteroPSLoad - PowerShell downloader.
|`+D5576E578518E474A5DFF654C44AB3EC4A6E4ECF+` |PowerShell/Pterodo.FD |PteroPSLoad - PowerShell downloader.
|`+28F4F0367C2BB0574C8A7D1B9C3E71E6AC678300+` |PowerShell/Pterodo.AV |PteroPSLoad - PowerShell downloader.
|`+E0BD8855159CB708789C4DE183E107C5C117FBA1+` |PowerShell/Pterodo.GE |PteroPSLoad - PowerShell downloader.
|`+9E30DFFDB88DD3ADFAB4CD5C67A98336C4BF9504+` |PowerShell/Pterodo.DX |PteroPSLoad - PowerShell downloader.
|`+224B18E531E511CEA2849D9A3B9CF5AD502AFECC+` |PowerShell/TrojanDownloader.Agent.EMF |PteroPSLoad - PowerShell downloader.
|`+6D694B73A2C497F16EB9B5CCA883658397FFBEDF+` |PowerShell/Agent.GT |PteroPSLoad - PowerShell downloader.
|`+B08305C557692619B9D0EAF5B58A8B91858CF4D5+` |Win32/Pterodo.BTM |PteroPSLoad - PowerShell downloader.
|`+B99D4724077B0A2CBEEE38332C05F3D4171C9DCC+` |PowerShell/Pterodo.AV |PteroPSLoad - PowerShell downloader.
|`+13BA279D8602FEE7CEDE152B6A9148CD9D2F6662+` |PowerShell/Pterodo.AV |PteroPSLoad - PowerShell downloader.
|`+8C9BFF48805537B41717BE78B1BE2A72DFC2A5D1+` |VBS/Pterodo.TT |Downloader of PteroPSLoad.
|`+E2FEEE0B92819AC7FCA85CFE3DC37750834F0990+` |PowerShell/Pterodo.GH |PteroPShell - PowerShell reverse shell.
|`+BED97E0CFEDA1588FF12B392E0B5502DB50DE768+` |PowerShell/Pterodo.GA |Downloader of PteroPShell.
|`+47A03EBB9798A8DF7EC8212134D418E937B449E9+` |Win32/TrojanDownloader.Pterodo.A |PteroPowder - downloads and executes a PowerShell payload.
|`+A93503BBB613F084ADD338B9FA2EEE466BF3A2D6+` |VBS/Pterodo.OD |PteroRisk - a VBScript general-purpose downloader.
|`+2B9B0AD0B65BB6101704684CD339E946FAE2DCFA+` |VBS/Pterodo.ABV |PteroSand - a VBScript general-purpose downloader.
|`+2416DFC031CF0D05054D5BEB9739CBA6470FE585+` |PowerShell/Pterodo.GO |PteroScout - gathers and exfiltrates various information about the compromised system.
|`+8C79BB8EB97E774FFCEC66C64F5CC8A11ED6C693+` |PowerShell/Pterodo.GL |Downloader of PteroScout.
|`+BA2366ED4E83FFC6DEC489C9011FE181CE169A47+` |PowerShell/Pterodo.BQ |PteroScreen - screen capturing tool.
|`+C42FE320A800F7C4AE97D0FDC6A1BBD91D57E75D+` |PowerShell/TrojanDownloader.Agent.HOI |Downloader of PteroScreen.
|`+2CDB1DA4DF1A33E379C2F24DD6A05709F4848CB6+` |PowerShell/Pterodo.FR |PteroSig - steals database that belongs to the Signal application.
|`+D37C80782FBEEE2035FBB196D6A6443B4BE05B4C+` |PowerShell/Pterodo.GA |Downloader of PteroSig.
|`+D58BFB39969F28698F90BF2E8782057E2F83C2DF+` |PowerShell/KillAV.AH |PteroSocks - SOCKS proxy.
|`+7CA1ADF40BA850D12B95259CBD2626562E17670C+` |PowerShell/Pterodo.GA |Downloader of PteroSocks.
|`+8A2261D8C8111D2D99276575120B9EA65D0AEAEA+` |PowerShell/Pterodo.EG |PowerShell version of PteroSteal - credential stealer.
|`+5E34D44D6B39ED1F97729184101185D368F2B6CE+` |PowerShell/Pterodo.GK |Downloader of PteroSteal.
|`+16FD6CBA3F13CC5B195CD6C0DD33BBF08CD0FE39+` |VBS/Pterodo.NM |PteroTemplate - Word template weaponizer.
|`+9A6B36E6CAD9156EA6E09DE740D3F1CCB6816F87+` |VBS/Pterodo.XX |PteroTemplate - Word template weaponizer.
|`+9E40CC45CBC9625EC190711D2790359A6198DB37+` |VBS/Pterodo.OC |PteroVDoor version 6004.
|`+0FD02B12517221F71A4A3774630C05643EE59988+` |VBS/Pterodo.ACF |PteroVDoor version 6005.
|`+596613AF85EE703858DB96C570C6C0283EAA19C6+` |VBS/TrojanDownloader.Agent.ZEK |Downloader of PteroVDoor.
|`+9B6EF236D9DC758336F1D89268822F8611C8B973+` |VBS/Pterodo.FE |Stage 1 of PteroVDoor download chain.
|`+CB9712BED15723973171192DA17946BF6778D98D+` |VBS/Pterodo.XR |Stage 2 of PteroVDoor download chain.
|`+04F1ED3050D6B2527D6196DFF5845B10510D0C2F+` |VBS/Pterodo.LS |Stage 2 of PteroVDoor download chain.
|`+5BEFC01A3771E61151224E18F926226FF7FD4A40+` |VBS/Pterodo.OC |ReVBShell - VBScript reverse shell.
|`+0B5402397306F702D006BC18A473DAC5CD33540B+` |Win32/Pterodo.CBG |Remote template downloaded by PteroDoc.
|`+F2D8F72F8FAA81AF02D31C5A93DFEA71E33DE0D9+` |VBA/Pterodo.BS |Remote template downloaded by PteroTemplate.
|===

=== Network IOCs

[options="header"]
|===
|IP |Domain |Hosting provider |First seen
|`+N/A+` |`+nododru[.]ru+` |N/A |2023-12-20
|`+5.252.178[.]140+` |`+N/A+` |MivoCloud SRL |2023-08-16
|`+194.180.191[.]30+` |`+N/A+` |MivoCloud Administrator, ORG-MS569-RIPE |2023-06-30
|`+N/A+` |`+amasiyagi[.]ru+` |N/A |2023-02-07
|`+N/A+` |`+t[.]me+` |N/A |2022-09-12
|`+N/A+` |`+opela[.]ru+` |N/A |2023-07-10
|`+141.98.233[.]17+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-08-17
|`+N/A+` |`+statuesque[.]ru+` |N/A |2023-09-25
|`+89.23.107[.]188+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-08-11
|`+212.18.104[.]56+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-08-04
|`+N/A+` |`+loturam[.]ru+` |N/A |2023-12-04
|`+N/A+` |`+telegra[.]ph+` |N/A |2023-06-20
|`+N/A+` |`+lokalut[.]ru+` |N/A |2023-10-09
|`+N/A+` |`+youdad[.]ru+` |N/A |2023-11-27
|`+N/A+` |`+marginisbi[.]ru+` |N/A |2023-07-11
|`+143.198.160[.]45+` |`+N/A+` |DigitalOcean, LLC |2023-10-16
|`+159.223.152[.]63+` |`+N/A+` |DigitalOcean, LLC |2023-07-10
|`+N/A+` |`+hulortad[.]ru+` |N/A |2022-05-06
|`+68.183.2[.]92+` |`+N/A+` |DigitalOcean, LLC |2023-11-02
|`+N/A+` |`+www.toorisugita[.]ru+` |N/A |2023-11-02
|`+N/A+` |`+filetransfer[.]io+` |N/A |2023-11-02
|`+159.203.14[.]8+` |`+N/A+` |DigitalOcean, LLC |2023-09-07
|`+N/A+` |`+dfgqdsd[.]ru+` |N/A |2023-11-09
|`+N/A+` |`+havxcq[.]ru+` |N/A |2023-08-30
|`+N/A+` |`+rieturc[.]ru+` |N/A |2023-06-20
|`+N/A+` |`+tolofa[.]ru+` |N/A |2023-08-04
|`+67.205.160[.]237+` |`+N/A+` |DigitalOcean, LLC |2023-04-11
|`+N/A+` |`+calendas[.]ru+` |N/A |2021-10-07
|`+N/A+` |`+alacritas[.]ru+` |N/A |2021-10-07
|`+N/A+` |`+corolain[.]ru+` |N/A |2021-11-11
|`+N/A+` |`+goloser[.]ru+` |N/A |2022-01-20
|`+N/A+` |`+retarus[.]ru+` |N/A |2022-01-20
|`+N/A+` |`+login.kifales[.]ru+` |N/A |2022-12-02
|`+N/A+` |`+hakold[.]ru+` |N/A |2022-12-15
|`+209.97.165[.]187+` |`+N/A+` |DigitalOcean, LLC |2023-08-18
|`+89.19.209[.]154+` |`+N/A+` |TimeWeb Ltd. |2023-10-02
|`+185.163.45[.]5+` |`+N/A+` |MivoCloud SRL |2023-06-12
|`+62.133.62[.]73+` |`+N/A+` |Evgenii M. |2023-12-20
|`+N/A+` |`+nikortal[.]ru+` |N/A |2023-12-06
|`+167.172.139[.]39+` |`+N/A+` |DigitalOcean, LLC |2023-10-23
|`+164.92.115[.]188+` |`+N/A+` |DigitalOcean, LLC |2023-08-30
|`+89.185.84[.]204+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-09-06
|`+195.133.88[.]128+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-09-29
|`+185.225.19[.]16+` |`+N/A+` |MivoCloud SRL |2023-08-18
|`+80.90.181[.]107+` |`+N/A+` |TimeWeb Ltd. |2023-05-22
|`+5.181.156[.]109+` |`+N/A+` |MivoCloud SRL |2023-06-21
|`+185.163.47[.]177+` |`+N/A+` |MivoCloud Administrator, ORG-MS569-RIPE |2023-11-01
|`+91.200.148[.]232+` |`+N/A+` |TimeWeb Ltd. |2023-08-24
|`+N/A+` |`+absorbeni[.]ru+` |N/A |2023-05-09
|`+N/A+` |`+consentesto[.]ru+` |N/A |2023-10-23
|`+46.29.234[.]46+` |`+N/A+` |GLOBAL CONNECTIVITY SOLUTIONS LLP |2023-09-18
|`+161.35.106[.]28+` |`+N/A+` |DigitalOcean, LLC |2023-09-18
|`+165.227.208[.]207+` |`+N/A+` |DigitalOcean, LLC |2023-09-30
|`+N/A+` |`+fritopa[.]ru+` |N/A |2023-09-30
|`+144.126.218[.]218+` |`+N/A+` |DigitalOcean, LLC |2023-09-20
|`+188.166.247[.]34+` |`+N/A+` |DigitalOcean, LLC |2023-06-21
|===

== Gamaredon group grows its game

The blog post about this group is available here https://www.welivesecurity.com/2020/06/11/gamaredon-group-grows-its-game/

=== Sample Hashes

[options="header"]
|========================================
|SHA-1 hash|Component|ESET Detection Name
|`6F75F2490186225C922FE605953038BDEB537FEE`|Outlook VBA module|DOC/TrojanDownloader.Pterodo.A
|`DFC941F365E065187B5C4A4BF42E770035920856`|C# Office macro injection module|Win32/Pterodo.XG.gen
|`9AFC9D6D72F78B2EB72C5F2B87BDC7D59C1A14ED`|Batch file/VBScript Office macro injection module|Win32/Pterodo.ZM
|`3DD83D7123AEFBE5579C9DC9CF3E68BCAFC9E65E`|C# compiler module|MSIL/Pterodo.CD
|`941F341770B67F9E8EE811B4B8383101F35B27CD`|GitHub project module|MSIL/Pterodo.CA
|`DC8BD2F65FD2199CE402C76A632A9743672EFE2D`|C/C++ backdoor|Win32/Pterodo.XC
|`336C1244674BB378F041E9064EA127E9E077D59D`|C# backdoor|MSIL/Pterodo.DP
|`5FC1B6A55A9F5A52422872A8E34A284CDBDD0526`|Batch file/VBScript backdoor|Win32/Pterodo.YE
|========================================

=== Network IOCs

==== Malicious domains linked to Gamaredon

```
abdurs.space
abies.space
actor-tv.ddns.net
acutifolia.space
addova.xyz
advansed-template.site
aganta.space
alastari.xyz
alenko.site
alenko.website
amarillio.space
anadima.website
apino.space
araino.space
arionda.space
armita.space
aromaticus.space
atropoides.space
aukci.space
babitors.myftp.biz
baby-tv.ddns.net
baill.space
barrigal.space
batmeast.space
bbtt.site
bbtt.space
bbtt.website
beasty.space
beepapa.space
beercraft.fun
beercraft.space
beercraft.website
benzoin.space
bergius.space
beriuatcj.hopto.org
bernado.website
birion.website
bits-mars.fun
bits-mars.info
bits-mars.site
bits-mars.space
bits-mars.website
bits-tor.fun
bits-tor.site
bits-tor.space
bits-tor.website
bitsadmin1.space
bitsadmin10.space
bitsadmin2.space
bitsadmin3.space
bitsadmin4.space
bitsadmin5.space
bitsadmin6.space
bitsadmin7.space
bitsadmin8.space
bitsadmin9.space
bitsbitsa.space
bitsbitsb.space
bitsbitsc.space
bitsbitsd.space
bitsbitsf.space
bitsbitsg.space
bitsbitsh.space
bitsbitsi.space
bitsbitsk.space
bitsbitsl.space
bizavto.myftp.org
blackardi.space
borigl.space
bowira.website
burago.space
callitris.space
caprjhjkqwer.hopto.org
cartu.myftp.org
caryophyllus.space
casopruy.myftp.org
cathartica.space
centifolia.space
cephaelis.space
cerasus.space
ceredukos.hopto.org
cereffiopas.hopto.org
certerasdfuj.hopto.org
ceyudfg.hopto.org
chachand.space
chairada.space
chamomilla.ru
changato.space
charika.website
cioasdg.hopto.org
cleaners.fun
codfgsdf.hopto.org
codfjert.myftp.org
comedas.space
copiran.space
coprtyuqw.hopto.org
cornelius.website
corovana.space
cosdfghdf.hopto.org
cowtor.space
cozsdv.hopto.org
cozxcgbx.myftp.org
cpasah.hopto.org
cpozsxcgbxf.myftp.org
crons.ddns.net
ctert.myftp.org
cubeba.space
cudawer.hopto.org
cudrg.myftp.org
cufjdfge.myftp.org
cuiasef.myftp.org
cupana.space
cyberworld.host
cyberworld.website
davaris.space
delile.space
deloperaw.bounceme.net
demiurg.fun
demiurg.site
demiurg.space
demiurg.website
denovar.space
derpenta.space
deviar.space
dilana.space
dolori.website
dorogavi.space
dortama.space
drovka.space
dryand.space
elecan.space
entona.website
eregorn.space
error-word.myftp.biz
erythrina.space
europaea.ru
excelsa.space
fangimen.xyz
farfara.space
fartiny.xyz
federeal.3utilities.com
feodal.bounceme.net
feridonutop.myftp.org
ferranot.xyz
fidel.freedynamicdns.org
fillin.space
firecor.space
firestarters.site
firran.xyz
fix-template.site
fizanta.space
flackch.space
foenum.space
forestac.site
forestac.website
forestac.xyz
fragrans.ru
frangula.space
frondo.xyz
frostani.website
fuagrado.space
fulo-tv.ddns.net
fuubara.space
gameland.host
gameland.space
gameland.website
gameworld.space
gameworld.website
gereston.gotdns.ch
gerotron.gotdns.ch
gerotumans.myftp.org
gerusta.space
get-icons.ddns.net
geterotuks.hopto.org
geters-tv.ddns.net
getro.bounceme.net
getyuawer.myftp.biz
gochir.space
godrick.space
gogora.space
gorgopa.xyz
goronta.website
gostio.website
grandiora.website
graveolens.space
groover.fun
groover.website
guitin.space
gulif.space
haker.fun
haker.host
haker.space
haker.website
hariva.space
harpa.site
harpa.space
harpa.website
hasuduwert.hopto.org
heartal.space
heavar.space
hedriks.bounceme.net
hestomig.hopto.org
himym.site
hirodomus.hopto.org
hispidus.space
hottob.space
houtt.ru
hres-tv.ddns.net
httpsnc.hopto.org
humulusa.ru
huncea.xyz
huugara.space
huvasi.website
hyditta.space
immortals.site
immortals.space
immortals.website
imperatoria.space
indicum.space
inogri.space
ip-server.freedynamicdns.net
isoga.space
itango.space
jdaeus.space
jeera.space
jgnatii.space
jikardo.myftp.org
jogara.space
jontap.xyz
karapuls.3utilities.com
karikatos.hopto.org
katalisto01.ddns.net
kelogir.myftp.biz
kilazurus.hopto.org
kilewqrt.hopto.org
kilosadwert.hopto.org
kiloster.bounceme.net
kilotrace.myftp.org
kiodas.xyz
kirasto.website
kistas-tv.ddns.net
kokoni.space
koleran.xyz
kolidus.gotdns.ch
kolinstro.space
korogav.space
krikorro.space
kristol.space
kristom.hopto.org
kristomen.myftp.org
krossin.website
krugotto.space
ksevada.space
landraba.website
laricio.space
lebrederm.space
lebreman.space
leeri.space
leronti.space
leucadendron.ru
libcrash.ddns.net
libda.site
libdab.site
libdac.site
libdad.site
libdade.site
libdadi.site
libdado.site
libdaf.site
libdag.site
libdah.site
libdak.site
libdal.site
libdam.site
libdan.site
libdas.site
liboot.myftp.biz
libre1.space
libre2.space
libre3.space
libre4.space
librerty.space
libres.space
libressimo.space
liferat.space
lifista.space
lindras.space
lionello.website
liqutan.xyz
lodafert.hopto.org
lodus.freedynamicdns.org
loomand.space
lopasir.bounceme.net
lopaverus.3utilities.com
louthi.space
lycopodium.ru
macros1.space
macros2.space
macros3.space
macros4.space
malaky.site
malaky.website
malaky.xyz
malio-tv.hopto.org
mallotus.ru
maltikor.website
mandicap.space
mapper.space
mardallo.space
margatti.space
margon.website
marmari.space
marrubium.ru
masseffect.fun
masseffect.site
masseffect.space
masseffect.website
matricaria.ru
mazdok.myftp.org
mediacentr.space
melos.myftp.biz
melroses.space
menyanthes.ru
mersi-tv.ddns.net
mestara.space
miragena.xyz
mirani.website
mirkwood.space
mishel.freedynamicdns.org
mokushi.space
mototo.fun
mototo.site
mototo.space
mototo.website
musata.space
musik-dreg.ddns.net
musik-file.ddns.net
musik-jiolter.ddns.net
musik-klo.ddns.net
musik-kreps.ddns.net
musik-lio.ddns.net
musik-lis.ddns.net
musik-lk.ddns.net
musik-oretus.ddns.net
musik-pit.ddns.net
musik-qas.ddns.net
musik-sa.ddns.net
myristica.ru
naligo.space
naomat.space
naveria.website
ncio.freedynamicdns.net
ncov-2020.hopto.org
ncov-2020.site
nebola.space
nebora.space
nenadi.space
new-template.site
niam.space
nikao.website
nikolosad.myftp.org
normal-template.site
normandia.fun
normandia.website
nubiran.space
obendo.space
oenanthe.ru
office-constructor.ddns.net
officinale.space
ogmar.fun
ogmar.site
ogmar.space
ogmar.website
ogremage.site
ogremage.space
ogremage.website
old-template.site
olida.xyz
onyxi.xyz
opatusir.hopto.org
operitors.myftp.org
opitrqwer.3utilities.com
oput.freedynamicdns.org
orangae.space
orlani.xyz
orlean.space
orlenndi.space
orteasd-tv.ddns.net
oteruiowert.ddns.net
overload.space
overload.website
overwatch.host
pankratios.myftp.org
pannora.website
paparitto.space
papatti.space
paperonni.space
papir.hopto.org
pardi-tv.ddns.net
pasucoorew.hopto.org
pasudukus.hopto.org
patran.space
patrici.space
paullinia.space
pennatifolius.space
pennyal.space
perafidors.hopto.org
periaorew.hopto.org
perlandi.space
pestani.space
petroselinum.space
phellandrium.ru
physostigma.space
piantra.website
picea.space
pilocarpus.space
pinus.space
piscidia.space
pistacia.space
plotor.space
poasdrwety.hopto.org
podagenus.hopto.org
podr-tv.ddns.net
pointerra.space
polandi.website
poletton.space
polindar.space
polygala.space
poporaca.website
porilis.space
poronoc.website
potatin.space
poyrag.space
predf-tv.ddns.net
pridafi.website
primaver.space
proponda.space
pterocarpus.space
punica.space
purshiana.space
quadrivalvis.space
quarta.space
quassia.space
quercus.space
quillaja.space
rabio.website
radonta.space
raggina.space
rainak.space
rantai.space
redukos.bounceme.net
reiloster.hopto.org
remeno.space
rheum.space
rhus.space
ricinus.space
riki.space
risko.hopto.org
roseum.space
rosmarinus.space
rossalt.space
roundi.space
rubus.space
rud.ddns.net
russic.website
saazer.space
sabdja.3utilities.com
sabinar.website
saccharum.space
saijar.gotdns.ch 
salivar.space
samail.space
samak-tv.ddns.net
samalo.space
samarutus.hopto.org
sambiras.myftp.org
santalum.space
saponaria.space
saprit.fun
saprit.site
saprit.space
saprit.website
sarakinod.myftp.biz
sarutnoum.hopto.org
sativum.space
satkower.3utilities.com
saveriutew.3utilities.com
savert-tv.hopto.org
saxifraga.space
scopolia.space
sehadus.3utilities.com
seletos.3utilities.com
sendobin.space
senega.space
serpyllum.space
serumondus.hopto.org
sesamum.space
sevena.space
sheppard.fun
sheppard.website
shiodai.space
shokoda.xyz
shoppersi.space
sidochan.space
silenser.fun
silenser.site
silenser.space
silenser.website
silenser.xyz
sinapis.space
skymage.fun
skymage.space
skymage.website
slonar.website
solonra.space
sonik.hopto.org
sorg.space
spirantra.space
srarda.space
stairu.space
stan-stana.fun
stan-stana.site
stan-stana.space
stan-stana.website
statsinfo.space
steinh.space
stenama.space
stereo-bit.fun
stereo-bit.site
stereo-bit.space
stereo-bit.website
stolina.website
stonewa.space
strychnos.space
styrax.space
succedanea.space
sylvestris.ru
symphytum.space
tamarindus.space
tarapi.space
tclvds.site
tekora.space
terihorew.hopto.org
teris-tv.ddns.net
termit.site
termit.space
termit.website
termits.fun
terokitos.hopto.org
tesla-getro.ddns.net
tesla-opt.ddns.net
tesla-preat.ddns.net
tesla-res.ddns.net
tesla-rt.ddns.net
tesla-tehno.ddns.net
tesla-ufis.ddns.net
thymus.space
tiamor.space
tilia.space
tinctorum.space
toqq.website
torrent-vnc.ddns.net
toxifera.space
traksa.space
trelial.xyz
trigonella.space
triticum.space
troubl.xyz
tussilago.space
tyctyc.ddns.net
ulmifolia.space
uncaria.space
underlord.site
underlord.space
upokan.xyz
urceola.space
urginea.space
usbqueshions.ddns.net
usitatissimum.ru
utilissima.ru
vabalt.space
valeriana.space
vantalio.space
venomart.space
veratrum.space
verbascum.space
veronis.space
vertigos.space
vestak.space
veterra.space
vibraska.website
victios.space
vidika.website
vinara.xyz
vinifera.space
violina.website
virtuz.xyz
viruanta.website
viscum.space
vitis.space
volotin.space
vomica.space
voyaget.myftp.biz
vratio.space
vulgare.space
watcher.host
wavera.space
wayto.host
wayto.website
weaman.space
wertlook.hopto.org
weweca.website
wifa.site
wifa.space
wifa.website
wifb.site
wifb.space
wifb.website
wifc.host
wifc.site
wifc.space
wifc.website
wifo.host
wifo.site
wifo.space
wifo.website
wifu.site
wifu.space
wifu.website
wifx.site
wify.space
wify.website
wiilasto.website
wildbar.space
win-apu.ddns.net
wordmacros.space
wostrigo.website 
writedoc.bounceme.net
xakep.fun
xakep.site
xakep.website
yiorewasdf.myftp.org
zanusson.website
zanzar.space
zaoeryuijas.hopto.org
zareton.space
zikoarew.myftp.biz
zingiber.space
```
