= Mumblehard Indicators of Compromise 

The full report about Mumblehard is available at
http://www.welivesecurity.com/wp-content/uploads/2015/04/mumblehard.pdf

The condensed blog post about Mumblehard is available at
http://www.welivesecurity.com/2015/04/29/unboxing-linuxmumblehard-muttering-spam-servers/

== Yara

The yara rule `mumblehard_packer.yar` detects ELF binaries used by Mumblehard
packer.

== Network

.UDP packets to
- `194.54.81.162` port 53

.TCP connections to
- `194.54.81.163` port 80 (Mumblehard backdoor)
- `194.54.81.163` port 54321 (Mumblehard proxy announce)
- `194.54.81.163` port 25 (Mumblehard spamming daemon)
- `194.54.81.164` port 25 (Mumblehard spamming daemon)

.HTTP requests with one of the following User-Agent pattern
- `Mozilla/5.0 (Windows NT 6.1; rv:7.0.1) Gecko/<1 or more digits>.<1 or more digits>.<1 or more digits> Firefox/7.0.1`
- `Mozilla/5.0 (Windows NT 6.1; rv:7.0.1) Gecko/20100101 Firefox/7.0.1`

== Remediation

Here are a few steps to find out if you are infected with Mumblehard and what
to do to remove the threat. Instructions are different for the two different
components related to Mumblehard: the backdoor and the spamming daemon.

WARNING: These instructions are provided without warranties. They are accurate
         to the best of our knowledge by the time they were published. At any
         time, the behaviour of Mumblehard can change in a way that these
         remediation instructions will be invalid.

=== Mumblehard backdoor

The Mumblehard backdoor executable file is usually installed in `/var/tmp/` or
`/tmp`. It has a randomly generated name. A _crontab_ entry executes the
backdoor every 15 minutes. Here is an exemple entry:

----
*/15 * * * * /var/tmp/qCVwOWA >/dev/null 2>&1
----

To list cron jobs that execute every 15 minutes for all users, one can run as
root:

[source, bash]
----
for user in $(cut -f1 -d: /etc/passwd); do
    jobs="$(crontab -l -u "$user" | grep '^*/15')"
    if [ "$jobs" ]; then
        echo "# User: $user"
        echo "$jobs"
    fi
done 2> /dev/null
----

The executable files listed can be scanned against the
link:mumblehard_packer.yar[] Yara rule for further verification. This step
requires https://plusvic.github.io/yara/[Yara] to be installed.

Removing the _crontab_ entry using (`crontab -e -u {affected_user}`) and
deleting the executable file should remove the Mumblehard backdoor.

CAUTION: Although the backdoor should now be inactive, the initial infection
         vector is still unknown, and you might get reinfected. Your usual
         incidence response techniques should be used, such as auditing for PHP
         backdoors and outdated software. Passwords should also be changed.

=== Mumblehard spamming daemon

Unlike the backdoor component, the spamming daemon is not persistant. It is,
most of the time, downloaded and launched by the backdoor. The daemon replaces
his process name with either `httpd`, `mail` or `init`. To identify the
process, we search for a process with one of these name but is actually running
under the Perl interpreter. The following command ran as root will print the
_pid_ of such processes on Linux:

----
ps -ef | grep -e ' httpd$' -e ' mail$' -e ' init$' | awk '{print $2}' | xargs -I '{}' ls -l '/proc/{}/exe' | grep perl | cut -d/ -f 3
----

The processes listed should then be analyzed to see if they are malicious. You
can see if they are currently sending e-mail messages by using:

----
lsof -n -i -p {pid} | grep :smtp
----

If you are sure the process is not legitimate, stop the process with

----
kill {pid}
----

CAUTION: Although the spamming daemon should now be inactive, the initial
         infection vector is still unknown, and you might get reinfected. Your
         usual incidence response techniques should be used, such as auditing
         for PHP backdoors and outdated software. Passwords should also be
         changed.
